<?php $helper = $this->helper("Prince\Buynow\Helper\Data"); ?>
<?php $formId = $helper->getAddToCartFormId(); ?>
<?php $buttonTitle = $helper->getButtonTitle() ?>
<div class="buynow-button">
    <button type="submit" title="<?php /* @escapeNotVerified */ echo __($buttonTitle) ?>" id="buy-now" class="action primary" data-mage-init='
    {
        "Prince_Buynow/js/buy-now": {
            "form": "#<?php echo $formId; ?>"
        }
    }
    '>
        <span><?php /* @escapeNotVerified */ echo __($buttonTitle) ?></span>
    </button>
</div>