<?php $product = $this->getProduct(); ?>
<?php if ($product->isSaleable()): ?>
	<?php $postParams = $block->getAddToCartPostParams($product); ?>
	<div class="product-item-inner buynow">
		<form action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" id="product_addtocart_form_<?php echo $postParams['data']['product']; ?>" method="post">
		    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
		    <input type="hidden" name="<?php /* @escapeNotVerified */ echo 'uenc'; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
		    <?php echo $block->getBlockHtml('formkey')?>
		    <button type="submit"
		            title="<?php echo $block->escapeHtml(__('Buy Now')); ?>"
		            class="action tocart buynow primary"
		            data-mage-init='
		            {
		                "Prince_Buynow/js/buy-now": {
		                    "form": "#product_addtocart_form_<?php echo $postParams['data']['product']; ?>"
		                }
		            }
		        '>
		        <span><?php /* @escapeNotVerified */ echo __('Buy Now') ?></span>
		    </button>
		</form>
	</div>
<?php endif; ?>