<?php $helper = $this->helper("Prince\Buynow\Helper\Data"); ?>
<?php $addtocartId = $helper->getConfig('buynow/general/addtocartid'); ?>
<?php $formId = $addtocartId ? $addtocartId : "product_addtocart_form"; ?>
<button type="submit" title="<?php /* @escapeNotVerified */ echo __('Buy Now') ?>" id="buy-now" class="action primary tocart" style="font-size: 1.8rem;padding: 17px 17px;
    width: 49%;" data-mage-init='
{
    "Prince_Buynow/js/buy-now": {
        "form": "#<?php echo $formId; ?>"
    }
}
'>
    <span><?php /* @escapeNotVerified */ echo __('Buy Now') ?></span>
</button>